### PR TITLE
add Graphistry

### PR DESCRIPTION
**Pull request by lmeyerov**
Technical distinguishers + primary library surface areas

### CODE REVIEW

**Comment by anvaka** [comment]
Thank you for the contribution! Is this an open source javascript library? I checked the website and couldn't tell right away. 

I don't mind starting a new section with commercial/non-open source solution, just want to be transparent about it

**Comment by lmeyerov** [comment]
Sure thing - Graphistry is a mix of OSS / free / paid, similar to the already-linked Linkurious

**Comment by lmeyerov** [comment]
. @anvaka saw this was still open in my gh feed, lmk if/how to land?

**Comment by anvaka** [comment]
Merged

**Pull request merged**
